### ISSUE TITLE
hwat is GEADJ?

### ISSUE THREAD

**Issue by flammie** [unimorph/fin#2]
There are a lot of occurrences of the analysis GEADJ in unimorph-fin but I didn't find it in the schema documentations?

E.g.
```
$ fgrep GEADJ fin/fin.1 | head
aakkosellinen	aakkosellisen	ADJ;GEADJ;SG
aakkosellinen	aakkosellisten	ADJ;GEADJ;PL
aakkosellisempi	aakkosellisemman	ADJ;GEADJ;SG
aakkosellisempi	aakkosellisempien	ADJ;GEADJ;PL
aakkosnumeerinen	aakkosnumeerisen	ADJ;GEADJ;SG
aakkosnumeerinen	aakkosnumeeristen	ADJ;GEADJ;PL
ääliömäinen	ääliömäisen	ADJ;GEADJ;SG
ääliömäinen	ääliömäisten	ADJ;GEADJ;PL
aalloittainen	aalloittaisen	ADJ;GEADJ;SG
aalloittainen	aalloittaisten	ADJ;GEADJ;PL

$ fgrep -c GEADJ fin/fin.1 
11462
```

It seems to appear with many denominal adjectives so maybe someone has run search and replace for `s/N/ADJ/`.

**Comment by kbatsuren** [comment]
Hi @flammie, thanks for raising this issue. 

The current update has fixed this issue. So I will close this issue. Feel free to open new issue if you find other issues from current update.
