### ISSUE TITLE
allomorphs are not included

### ISSUE THREAD

**Issue by flammie** [unimorph/fin#3]
A lot of Finnish paradigms exhibit free variation but it seems that the data only contains one form per tag-string, maybe by design. E.g. _päärynä_ in https://en.wiktionary.org/wiki/p%C3%A4%C3%A4ryn%C3%A4#Finnish:

| Inflection of päärynä (Kotus type 11/omena, no gradation) |

| päärynä | päärynät |
| päärynän | päärynien päärynöiden päärynöitten |
| päärynää | pääryniä päärynöitä |
| päärynään | pääryniin päärynöihin|

vs. fin.1:

```
päärynä päärynään       N;IN+ALL;SG
päärynä päärynää        N;PRT;SG
päärynä päärynäksi      N;TRANS;SG
päärynä päärynällä      N;AT+ESS;SG
päärynä päärynälle      N;AT+ALL;SG
päärynä päärynältä      N;AT+ABL;SG
päärynä päärynä N;ACC;SG
päärynä päärynänä       N;FRML;SG
päärynä päärynän        N;GEN;SG
päärynä päärynä N;NOM;SG
päärynä päärynässä      N;IN+ESS;SG
päärynä päärynästä      N;IN+ABL;SG
päärynä päärynät        N;ACC;PL
päärynä päärynät        N;NOM;PL
päärynä päärynättä      N;PRIV;SG
päärynä pääryniä        N;PRT;PL
päärynä päärynien       N;GEN;PL
päärynä pääryniin       N;IN+ALL;PL
päärynä päärynöiksi     N;TRANS;PL
päärynä päärynöillä     N;AT+ESS;PL
päärynä päärynöille     N;AT+ALL;PL
päärynä päärynöiltä     N;AT+ABL;PL
päärynä päärynöinä      N;FRML;PL
päärynä päärynöineen    N;COM;PL
päärynä päärynöin       N;INS;PL
päärynä päärynöissä     N;IN+ESS;PL
päärynä päärynöistä     N;IN+ABL;PL
päärynä päärynöittä     N;PRIV;PL
```

This problem applies to all words in paradigms that have free variation as well as all words that have free variation in vowel harmony.

**Comment by kbatsuren** [comment]
I am aware of this issue. As soon as I find a time, I will fix this issue.

**Comment by kbatsuren** [comment]
Hi @flammie, I am sorry for taking this long. The current update fixed this issue. So I am closing the issue. :)
